### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by jd2rogers2** [learn-co-curriculum/rendering-collections-lab#3]
worked through this with Adam this morning. here's the error

Failures:

  1) orders_index_view renders the order partial
     Failure/Error: <% @orders.each do |order| %>

```
 ActionView::Template::Error:
   undefined method `each' for #<Order:0x007fa34d2c1648>
 # ./app/views/orders/index.html.erb:9:in `_app_views_orders_index_html_erb__47327540943352512_70169675518120'
 # ./spec/views/orders_index_view_spec.rb:29:in `block (2 levels) in <top (required)>'
 # ------------------
 # --- Caused by: ---
 # NoMethodError:
 #   undefined method `each' for #<Order:0x007fa34d2c1648>
 #   ./app/views/orders/index.html.erb:9:in `_app_views_orders_index_html_erb__47327540943352512_70169675518120'
```

the controller is passing in @orders as @orders = Order.all but adam noticed that the tests are passing in Order.first looks like from line 27 in spec/views/orders_index_view_spec.rb

and i believe the same thing was happening with the first test too from line 28 of spec/views/invoices_index_view_spec.rb

**Comment by AnnJohn** [comment]
hi @jd2rogers2 this looks like an issue specific to your code, could you use Ask a Question and someone from our team will help you out. Thanks!

**Comment by jd2rogers2** [comment]
hi @AnnJohn i actually had already used Ask a Question and was told to raise an issue by adam king (instructor). the weird error is actually caused by the code that is included with the lab. it comes from app/views/orders/index.html.erb line 9. the .each method was there when i cloned the lab. happy to explain further if necessary and can be reached on slack with same username

**Comment by AnnJohn** [comment]
hi @jd2rogers2 thanks for clarifying. re-opening this issue. if you could explain a little bit further about where the problem is coming from (screenshots too would be helpful), that would be great.

**Comment by jd2rogers2** [comment]
here's a screenshot of what i'm looking at, this is the lab from the start as i just cloned a fresh one. you can see the error on the left in my terminal and the 3 related files in sublime on the right. in the top right you'll see the controller which should pass an array to the view (middle right) and therefore calling .each shouldn't be an issue but the test looks to be overriding somehow(???) with line 28/29/30 (now in specs on bottom right) passing in Invoice.first. it is also doing the same thing for the orders view

![screen shot 2016-08-23 at 10 14 41 am](https://cloud.githubusercontent.com/assets/16400333/17895243/7c8aec14-691a-11e6-9862-17367ec6b324.png)
