### ISSUE TITLE
Wrong directions

### ISSUE THREAD

**Issue by aisayo** [learn-co-curriculum/rendering-collections-lab#6]
Hello, Instructions say to refractor the two files that are not available as opposed to telling the student to create and extract. A bit confusing

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
